baseurl         = "https://tomutomu.netlify.com/"
theme           = "casper-two"
languageCode    = "js"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Ident"
  subtitle    = "だらだらとしたためる日記のようなもの"
  copyright   = "© 2019"

  cover       = "img/blog-cover.jpg"
  description = "だらだらとしたためる日記のようなもの"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = ""
  linkedinName = ""
  mediumName = ""

#  logo = "hugo-logo.png"
  orgName = "Ident!"
  orgWebsite = false
#  orgWebsite = "https://www.telematika.org"
#  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "HM"
  authorAvatar = "img/auther-icon.jpg"
#  authorLocation = "Bandung, ID"
#  authorWebsite = "https://eueung.github.io"
#  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

#[[menu.main]]
#  name = "タグ"
#  url = "/tags/"
#  weight = 100

[[menu.main]]
  name = "カテゴリー"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "デンマーク留学"
  url = "http://tomubox.hatenablog.com"
  weight = 95
